name: Update 5 Verst Data

on:
  schedule:
    # 10:00 UTC = 13:00 по Москве (Суббота)
    - cron: '0 10 * * 6'
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: py-actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: python script.py
