name: Run Kstovo Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Перезапуск каждые 6 часов для стабильности
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install vk_api

      - name: Run Bot
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: python bot.py
