name: VK Widget and Weather

on:
  schedule:
    - cron: '0 * * * *' # Каждый час (например, 10:00, 11:00...)
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Run Bot
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_CHAT_IDS: ${{ secrets.VK_CHAT_IDS }}
        run: python bot.py
