name: VK Widget and Weather

on:
  schedule:
    - cron: '0 * * * *' # Каждый час
  workflow_dispatch:
    inputs:
      force_weather:
        description: 'Отправить погоду принудительно?'
        required: true
        default: 'false'
        type: boolean

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Run Bot
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_CHAT_IDS: ${{ secrets.VK_CHAT_IDS }}
          FORCE_WEATHER: ${{ github.event.inputs.force_weather }}
        run: python bot.py
